Append job id to builder & context
Stops parallel jobs clashing

diff --git a/.gitlab/docker-build.yml b/.gitlab/docker-build.yml
--- a/.gitlab/docker-build.yml
+++ b/.gitlab/docker-build.yml
@@ -30,6 +30,8 @@ docker-build-dev:
     - docker run --rm --privileged aptman/qus -s -- -p aarch64 x86_64
     - echo $CI_JOB_TOKEN | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
     - echo $DOCKERHUB_TOKEN | docker login -u "$DOCKERHUB_USER" --password-stdin $DOCKERHUB_REGISTRY
+    - docker context create tls-environment-$CI_JOB_ID
+    - docker buildx create --name zedBuilder-$CI_JOB_ID --use tls-environment-$CI_JOB_ID
   script:
     - |
       tag=":$CI_COMMIT_REF_SLUG"
@@ -37,8 +39,6 @@ docker-build-dev:
     - |
       echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
       echo "Crafty Version: $VERSION"
-    - docker context create tls-environment
-    - docker buildx create --name zedBuilder --use tls-environment
     - docker buildx build
       --cache-from type=registry,ref="$CI_REGISTRY_IMAGE${tag}"
       --build-arg BUILDKIT_INLINE_CACHE=1
@@ -52,8 +52,8 @@ docker-build-dev:
       --push .
   after_script:
     - |
-      docker buildx rm zedBuilder && echo "Successfully Stopped builder instance" || echo "Failed to stop builder instance."
-      docker context rm tls-environment || true
+      docker buildx rm zedBuilder-$CI_JOB_ID && echo "Successfully Stopped builder instance" || echo "Failed to stop builder instance."
+      docker context rm tls-environment-$CI_JOB_ID || true
       echo "Please review multi-arch manifests are present:"
       docker buildx imagetools inspect "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
 
@@ -87,6 +87,8 @@ docker-build-prod:
     - docker run --rm --privileged aptman/qus -s -- -p aarch64 x86_64
     - echo $CI_JOB_TOKEN | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
     - echo $DOCKERHUB_TOKEN | docker login -u "$DOCKERHUB_USER" --password-stdin $DOCKERHUB_REGISTRY
+    - docker context create tls-environment-$CI_JOB_ID
+    - docker buildx create --name zedBuilder-$CI_JOB_ID --use tls-environment-$CI_JOB_ID
   script:
     - |
       VERSION="${MAJOR}.${MINOR}.${SUB}"
@@ -110,7 +112,7 @@ docker-build-prod:
       --push .
   after_script:
     - |
-      docker buildx rm zedBuilder && echo "Successfully Stopped builder instance" || echo "Failed to stop builder instance."
-      docker context rm tls-environment || true
+      docker buildx rm zedBuilder-$CI_JOB_ID && echo "Successfully Stopped builder instance" || echo "Failed to stop builder instance."
+      docker context rm tls-environment-$CI_JOB_ID || true
       echo "Please review multi-arch manifests are present:"
       docker buildx imagetools inspect "$CI_REGISTRY_IMAGE${tag}"
